# Generated by Django 4.0.4 on 2022-05-24 17:16


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digipet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(choices=[('H', 'Huskey'), ('C', 'Corgi'), ('O', 'Otter')], max_length=10)),
                ('personality', models.CharField(choices=[('T', 'Timid'), ('B', 'Brave'), ('N', 'Naughty'), ('C', 'Calm'), ('J', 'Jolly'), ('Q', 'Quirky'), ('S', 'Sassy')], max_length=20)),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
