
# Generated by Django 4.0.4 on 2022-05-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_digipet_personality_alter_digipet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='digipet',
            name='mood',
            field=models.CharField(choices=[('Ha', 'Happy'), ('Hu', 'Hungry'), ('S', 'Smelly'), ('B', 'Bored'), ('R', 'Restless')], default='Ha', max_length=20),
        ),
    ]
