# Generated by Django 4.0.4 on 2022-05-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digipet',
            name='personality',
            field=models.CharField(choices=[('T', 'Timid'), ('B', 'Brave'), ('N', 'Naughty'), ('C', 'Calm'), ('J', 'Jolly'), ('Q', 'Quirky'), ('S', 'Sassy')], default='T', max_length=20),
        ),
        migrations.AlterField(
            model_name='digipet',
            name='species',
            field=models.CharField(choices=[('H', 'Huskey'), ('C', 'Corgi'), ('O', 'Otter')], default='H', max_length=10),
        ),
    ]
