# Generated by Django 4.0.4 on 2022-05-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_digipet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digipet',
            name='image',
        ),
    ]
