# Generated by Django 4.0.4 on 2022-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_digipet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digipet',
            name='image',
            field=models.CharField(default='/static/digipets/assets/animals/corgi/1.svg', max_length=250),
        ),
    ]
