# Generated by Django 4.0.4 on 2022-05-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_digipet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digipet',
            name='image',
            field=models.ImageField(default='/static/digipets/assets/animals/otter/1.svg', upload_to=''),
        ),
    ]
